### ISSUE TITLE
Base structure & requirements

### ISSUE THREAD

**Issue by jstoiko** [raml-org/playground#1]
## Structure
- top bar has:
  - RAML SVG logo on left
  - dropdown menu linking different demos on right, prefixed by text: "Demo: "

## Requirements
- host on GH pages
- reuse [amf-playground](https://github.com/aml-org/amf-playground) as a base for html/visual libraries/etc
- use new raml.org's [CSS](https://github.com/raml-org/raml-org/blob/stg/css/style.scss) - see [current staging site](https://stg.raml.org)
- use [webapi-parser](https://github.com/raml-org/webapi-parser) (not AMF directly)
- use same [Monaco Editor and CSS](https://github.com/raml-org/raml-org/tree/develop/min/vs) as on new raml.org's site

**Comment by postatum** [comment]
- [ ] RAML SVG logo on left in top bar
- [ ] dropdown menu linking different demos on right, prefixed by text: "Demo: " in top bar
- [ ] host on GH pages
- [ ] reuse amf-playground as a base for html/visual libraries/etc
- [ ] use new raml.org's CSS - see current staging site
- [ ] use webapi-parser (not AMF directly)
- [ ] use same Monaco Editor and CSS as on new raml.org's site

**Comment by postatum** [comment]
All requirements are met.
