### ISSUE TITLE
Add "Diff" demo

### ISSUE THREAD

**Issue by jstoiko** [raml-org/playground#19]
- [x] use "old" amf playground "diffing demo" for inspiration
- [x] Monaco has a [Diffing Editor built-in](https://microsoft.github.io/monaco-editor/playground.html#creating-the-diffeditor-hello-diff-world)

**Comment by postatum** [comment]
Changes for this issue are contained in two branches:
`i19_diff_demo`: Contains old Diff demos reworked with new features and webapi-parser;
`i19_diff_demo_monaco`: Contains Diff demo implemented using Monaco Diff editor.
