### ISSUE TITLE
"Visualization" demo

### ISSUE THREAD

**Issue by jstoiko** [raml-org/playground#2]
- [x] add "Visualization" link to top-right dropdown menu
- [x] side by side view: RAML editor vs Graph Representation[1]
- [x] when a graph element is selected, highlight RAML text

[1] similar to "Graph" tab of https://a.ml/amf-playground/playground.html

**Comment by postatum** [comment]
Merged in master.
Is hosted ad https://raml-org.github.io/playground/visualization.html

**Comment by postatum** [comment]
Will close this issue and address issues/feedback in new ones.
