### ISSUE TITLE
"RAML + OAS" demo

### ISSUE THREAD

**Issue by jstoiko** [raml-org/playground#3]
- [x] add "RAML + OAS" link to top-right dropdown menu
- [x] side by side (50/50 split) view: RAML (Monaco editor) vs OAS (Monaco editor)
- [x] modifying one side updates the other in "realtime"

**Comment by postatum** [comment]
[ ] rework using `webapi-parser`

**Comment by postatum** [comment]
Merged in `master`.
Is hosted ad https://raml-org.github.io/playground/raml_oas.html

**Comment by postatum** [comment]
Will close this issue and address issues/feedback in new ones.
