### ISSUE TITLE
add a way to dynamically load RAML files

### ISSUE THREAD

**Issue by jstoiko** [raml-org/playground#6]
- [x] ability to pass a RAML file as a query parameter in the URL of the playground[1]
- [x] ability to load files from any domain e.g. gist.github.com[2]

[1] E.g. `https://raml-org.github.io/playground/visualization.html?raml=` where `raml` can either be a URL-encoded string representing the content of the RAML file or a URL (e.g. `https://raml-org.github.io/playground/samples/api.raml`)
[2] CORS might be an issue if trying to load files from other domains though. If no trivial solution, let's address that bit later and create a separate issue to track it

**Comment by postatum** [comment]
Implemented and merged into `master`.

RAML can now be loaded via:
* URL from playground pages by clicking "Load RAML File" button and specifying URL.
* Providing URL to a RAML file as `?raml=` query param value
* Providing URL-encoded RAML file content as `?raml=` query param value

--- 
Examples of URL as query param value:

https://raml-org.github.io/playground/visualization.html?raml=https://gist.githubusercontent.com/postatum/c0f468f5d9049d429cfb1c8934ff09f7/raw/1738397d7cfe375536f662b09f2a8ef2b7d25af2/foo-api.raml

https://raml-org.github.io/playground/raml_oas.html?raml=https://gist.githubusercontent.com/postatum/c0f468f5d9049d429cfb1c8934ff09f7/raw/1738397d7cfe375536f662b09f2a8ef2b7d25af2/foo-api.raml

Examples of RAML content as query param value:

https://raml-org.github.io/playground/visualization.html?raml=%23%25RAML%201.0%0Atitle%3A%20API%20with%20Types%0Atypes%3A%0A%20%20User%3A%0A%20%20%20%20type%3A%20object%0A%20%20%20%20properties%3A%0A%20%20%20%20%20%20firstName%3A%20string%0A%20%20%20%20%20%20lastName%3A%20%20string%0A%20%20%20%20%20%20age%3A%0A%20%20%20%20%20%20%20%20type%3A%20integer%0A%20%20%20%20%20%20%20%20minimum%3A%200%0A%20%20%20%20%20%20%20%20maximum%3A%20125%0A%2Fusers%2F%7Bid%7D%3A%0A%20%20get%3A%0A%20%20%20%20responses%3A%0A%20%20%20%20%20%20200%3A%0A%20%20%20%20%20%20%20%20body%3A%0A%20%20%20%20%20%20%20%20%20%20application%2Fjson%3A%0A%20%20%20%20%20%20%20%20%20%20%20%20type%3A%20User

https://raml-org.github.io/playground/raml_oas.html?raml=%23%25RAML%201.0%0Atitle%3A%20API%20with%20Types%0Atypes%3A%0A%20%20User%3A%0A%20%20%20%20type%3A%20object%0A%20%20%20%20properties%3A%0A%20%20%20%20%20%20firstName%3A%20string%0A%20%20%20%20%20%20lastName%3A%20%20string%0A%20%20%20%20%20%20age%3A%0A%20%20%20%20%20%20%20%20type%3A%20integer%0A%20%20%20%20%20%20%20%20minimum%3A%200%0A%20%20%20%20%20%20%20%20maximum%3A%20125%0A%2Fusers%2F%7Bid%7D%3A%0A%20%20get%3A%0A%20%20%20%20responses%3A%0A%20%20%20%20%20%20200%3A%0A%20%20%20%20%20%20%20%20body%3A%0A%20%20%20%20%20%20%20%20%20%20application%2Fjson%3A%0A%20%20%20%20%20%20%20%20%20%20%20%20type%3A%20User

**Comment by postatum** [comment]
Will close this issue and address issues/feedback in new ones.
