### ISSUE TITLE
Address OAS+RAML feedback (pt.1)

### ISSUE THREAD

**Issue by postatum** [raml-org/playground#9]
~- [ ] 1) any way scrolling one document could scroll the other by preserving the same position in the document (not the same line, the same node representing the response/request/method/etc being viewed)?~
- [x] 2) the OAS 2.0 document should be in YAML instead of JSON
- [x] 3) would it be doable to have the "Load RAML file" pop-up have some sort of "document navigator" that allows me to pick any RAML file contained in the raml-org/raml-examples repo? can you try to think of the best way to achieve this?

**Comment by postatum** [comment]
>  2) the OAS 2.0 document should be in YAML instead of JSON

This will rely on changes from this PR being merged and released https://github.com/raml-org/webapi-parser/pull/25

**Comment by postatum** [comment]
Also fixed jumping cursor as noted in this comment: https://github.com/aml-org/amf-playground/pull/28#pullrequestreview-241982361

The cursor still jumps in an editor that is not being changed because it's value is regenerated.

**Comment by postatum** [comment]
All the changes are in `i9_oasraml_feedback` branch.

**Comment by jstoiko** [comment]
for some reason, when I load a RAML file, it only shows up as OAS on the right side, the left side RAML side remains empty

**Comment by postatum** [comment]
> For some reason, when I load a RAML file, it only shows the OAS version on the right side, the left side (RAML side) remains empty. It only happens with the `i9_oasraml_feedback` branch though (not current master/github pages) so maybe you're still working on it? if so, will comment on the PR once it's ready.

Thanks for reporting this issue. I broke files loading when was fixing jumping cursor in editors. Fixed.

**Comment by postatum** [comment]
Trying to implement 1) in branch `i9_oasraml_feedback_scroll_docs`

**Comment by postatum** [comment]
Examples to use with this demo

https://raw.githubusercontent.com/raml-org/raml-examples/master/typesystem/simple.raml

https://raw.githubusercontent.com/raml-org/raml-examples/master/typesystem/complex.raml

**Comment by postatum** [comment]
@jstoiko 

>  1) any way scrolling one document could scroll the other by preserving the same position in the document (not the same line, the same node representing the response/request/method/etc being viewed)?

I've tried to implement it but there's a lot of corner cases. Should I continue or should we create a separate issue and work on it later?

**Comment by postatum** [comment]
@jstoiko 

> 3) would it be doable to have the "Load RAML file" pop-up have some sort of "document navigator" that allows me to pick any RAML file contained in the raml-org/raml-examples repo? can you try to think of the best way to achieve this?

Not navigator but a dropdown with a list of raml files from raml-examples repo. We could generate a json file when running demo locally and store it in repo. When demo is loaded we generate a dropdown from that json file. As for generating json file with a list of raml files - it's possible to to do with `git clone; cd; git ls-files` and some output filtering & redirect.

Should I implement it?

**Comment by jstoiko** [comment]
Have you considered using Github Contents API[1]? I was thinking something along those lines: https://scotch.io/tutorials/create-a-github-file-explorer-using-vue-js

If that doesn’t work for whatever reason, sure, let’s use a JSON, maybe even a static one with only the main RAML examples in that repo, same as what we had before in the amf-playground. Good enough for now I guess.

[1] https://developer.github.com/v3/repos/contents/#get-contents

**Comment by jstoiko** [comment]
> @jstoiko
> 
> > 1. any way scrolling one document could scroll the other by preserving the same position in the document (not the same line, the same node representing the response/request/method/etc being viewed)?
> 
> I've tried to implement it but there's a lot of corner cases so implementing a complete version would take some time. Should I continue or should we create a separate issue and work on it later?

that’s fine.

**Comment by postatum** [comment]
> Have you considered using Github Contents API[1]? I was thinking something along those lines: https://scotch.io/tutorials/create-a-github-file-explorer-using-vue-js
> 
> If that doesn’t work for whatever reason, sure, let’s use a JSON, maybe even a static one with only the main RAML examples in that repo, same as what we had before in the amf-playground. Good enough for now I guess.
> 
> [1] https://developer.github.com/v3/repos/contents/#get-contents

Oh nice. I didn't find those endpoints when I was looking at github API.
I've implemented it using the API but still made it a select with options. I did this because I couldn't find an easy way to implement a "file explorer" since our demos are static for the most part and file explorer will require rendering html on the fly.
